# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 057e3c1f0c89ca3bf61e6698074a4196b9e85a7893303034f425a9cf8d11594462217c3d184a261148383d5e494f8348fcd94048c9245b03755d2461a44de03e

test:
  secret_key_base: d0a9409c7d258bfc2ba5ad4af1e5f2964bd4033ebf532429297d5845d53148d0c8b44904bb530d9b032e27844dd0e6590e304be7dbcacebe8333fd8edab0535f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
